// client-Vue-js/pokedex-vue/src/App.vue
<template>
  <main class="container mx-auto flex flex-col">
    <h1 class="title">Pokedex</h1>
    <form @submit.prevent="addPokemon" class="form">
      <h2 class="subtitle">Agregar nuevo pokemon</h2>
      <input type="number" v-model="newPokemon.id" placeholder="ID" class="input" />
      <input type="text" v-model="newPokemon.name" placeholder="Name" class="input" />
      <button type="submit" class="submit-button">Agregar</button>
    </form>
    <ul class="pokemon-list">
      <li class="list-header">
        <span class="text-lg text-white font-extrabold w-1/3">ID</span>
        <span class="text-lg text-white font-extrabold w-1/3 text-center">Name</span>
        <span class="text-lg text-white font-extrabold w-1/3 text-right">DELETE</span>
      </li>
      <li v-for="pokemon in pokemons" :key="pokemon.id" class="list-item">
        <span class="text-lg text-red-600 font-bold w-1/3">{{ pokemon.id }}</span>
        <span class="text-lg text-red-600 font-bold w-1/3 text-center">{{ pokemon.name }}</span>
        <button @click.prevent="deletePokemon(pokemon.id)" class="delete-button">
          X
        </button>
      </li>
    </ul>
  </main>
</template>

<script>
import axios from 'axios'

export default {
  data () {
    return {
      pokemons: [],
      newPokemon: {
        id: null,
        name: ''
      }
    }
  },
  mounted () {
    this.getPokemons()
  },
  methods: {
    async getPokemons () {
      try {
        const response = await axios.get('http://localhost:4321/api/pokemon')
        this.pokemons = response.data
      } catch (error) {
        console.error('Error fetching pokemons:', error)
      }
    },
    async addPokemon () {
      try {
        await axios.post('http://localhost:4321/api/pokemon', this.newPokemon)
        this.getPokemons()
        this.newPokemon.id = null
        this.newPokemon.name = ''
      } catch (error) {
        console.error('Error adding pokemon:', error)
      }
    },
    async deletePokemon (id) {
      try {
        await axios.delete(`http://localhost:4321/api/pokemon/${id}`)
        this.getPokemons()
      } catch (error) {
        console.error('Error deleting pokemon:', error)
      }
    }
  }
}
</script>

<style scoped>
.title {
  text-align: center;
  font-size: 5rem;
  color: #c53030;
  font-weight: 800;
}

.subtitle {
  font-size: 2rem;
  color: #c53030;
  font-weight: 700;
}

.form {
  margin-top: 2rem;
}

.input {
  margin-top: 1rem;
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #cbd5e0;
  border-radius: 0.375rem;
}

.submit-button {
  width: 100%;
  padding: 0.5rem;
  background-color: #c53030;
  color: white;
  border-radius: 0.375rem;
  margin-top: 0.5rem;
  font-weight: bold;
  text-transform: uppercase;
}

.pokemon-list {
  margin-top: 4rem;
  border: 4px solid #c53030;
}

.list-header {
  display: flex;
  justify-content: space-between;
  border-bottom: 1px solid #cbd5e0;
  padding: 2rem;
  background-color: #c53030;
}

.list-item {
  display: flex;
  justify-content: space-between;
  border-bottom: 1px solid #cbd5e0;
  padding: 2rem;
}

.delete-button {
  font-weight: bold;
  cursor: pointer;
}
</style>

// reactapp/src/App.tsx
import { useEffect, useState } from "react";

type Creature = {
  id: number;
  name: string;
};

const API_URL = 'http://localhost:4321/api';

export default function App() {
  const [creatures, setCreatures] = useState<Creature[]>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalCreatures, setTotalCreatures] = useState(0);

  const loadCreatures = async () => {
    const response = await fetch(`${API_URL}/pokemon.json?page=${currentPage}`);
    const data = await response.json();
    setCreatures(data.list);
    setTotalCreatures(data.count);
  };

  useEffect(() => {
    loadCreatures();
  }, [currentPage]);

  const createCreature = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const form = event.currentTarget;
    const formData = new FormData(form);
    const creature = {
      id: parseInt(formData.get('id') as string),
      name: formData.get('name') as string,
    };

    await fetch(`${API_URL}/pokemon.json`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(creature),
    });

    form.reset();
    if (currentPage === Math.ceil(totalCreatures / 5) && creatures.length < 5) {
      setCreatures((current) => [...current, creature]);
    }
    setTotalCreatures((current) => current + 1);
  };

  const removeCreature = async (id: number) => {
    await fetch(`${API_URL}/pokemon/${id}.json`, {
      method: 'DELETE',
    });

    setCreatures((current) => current.filter((creature) => creature.id !== id));
    setTotalCreatures((current) => current - 1);

    if (currentPage > Math.ceil((totalCreatures - 1) / 5)) {
      setCurrentPage(currentPage - 1);
    }
  };

  return (
    <main className="container mx-auto flex flex-col">
      <h1 className="text-5xl text-red-600 font-extrabold text-center">Pokedex</h1>
      <form action="/api/pokemon" method="post" onSubmit={createCreature}>
        <h2 className="text-2xl text-red-700 font-bold">Agregar nuevo pokemon</h2>
        <input type="number" name="id" placeholder="ID" className="my-1 w-full p-2 border border-gray-300 rounded-lg" />
        <input type="text" name="name" placeholder="Name" className="my-1 w-full p-2 border border-gray-300 rounded-lg" />
        <button type="submit" className="w-full p-2 bg-red-600 text-white rounded-lg mt-2 font-bold uppercase duration-200 hover:bg-red-700">Agregar</button>
      </form>
      <ul className="mt-4 border-4 border-red-700">
        <li className="flex items-center justify-between border-b border-gray-300 p-2 bg-red-700">
          <span className="text-lg text-white font-extrabold w-1/3">ID</span>
          <span className="text-lg text-white font-extrabold w-1/3 text-center">Name</span>
          <span className="text-lg text-white font-extrabold w-1/3 text-right">DELETE</span>
        </li>
        {creatures.map(creature => (
          <li className="flex items-center justify-between border-b border-gray-300 p-2">
            <span className="text-lg text-red-600 font-bold w-1/3">{creature.id}</span>
            <span className="text-lg text-red-600 font-bold w-1/3 text-center">{creature.name}</span>
            <div className="w-1/3 text-right">
              <button onClick={() => removeCreature(creature.id)} className="font-bold hover:font-extrabold">X</button>  
            </div>
          </li>
        ))}
      </ul>
      <div className="flex justify-center gap-2">
        <button onClick={() => setCurrentPage(c => Math.max(1, c - 1))} disabled={currentPage === 1} className="p-2 bg-red-600 text-white rounded-lg mt-2 font-bold uppercase duration-200 disabled:opacity-50 hover:bg-red-700">Prev</button>
        <span className="flex items-center self-stretch">{currentPage}</span>
        <button onClick={() => setCurrentPage(c => Math.min(Math.ceil(totalCreatures / 5), c + 1))} disabled={currentPage === Math.ceil(totalCreatures / 5)} className="p-2 bg-red-600 text-white rounded-lg mt-2 font-bold uppercase duration-200 disabled:opacity-50 hover:bg-red-700">Next</button>
      </div>
    </main>
  );
}
